name: minden
description: minden app

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.9.2
  mockito: ^5.0.7
  equatable: ^2.0.0
  get_it: ^7.1.3
  flutter_bloc: ^7.0.0
  data_connection_checker: ^0.3.4
  url_launcher: ^6.0.3
  flutter_i18n: ^0.22.3
  sprintf: ^6.0.0
  package_info: ^2.0.0
  version: ^2.0.0
  shared_preferences: ^2.0.5

  bot_toast: ^4.0.1
  after_layout: ^1.1.0

  firebase_core_platform_interface: ^2.0.0
  firebase_core: ^0.5.3
  firebase_remote_config: ^0.4.3
  firebase_analytics: ^6.3.0
  firebase_crashlytics: ^0.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^1.0.0

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/i18n/

