name: minden
description: minden app

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0-nullsafety.2
  equatable: ^2.0.0
  get_it: ^7.1.3
  flutter_bloc: ^7.0.0
  connectivity: ^3.0.6
  url_launcher: ^6.0.3
  flutter_i18n: ^0.22.3
  sprintf: ^6.0.0
  package_info: ^2.0.0
  version: ^2.0.0
  shared_preferences: ^2.0.5

  mockito: ^5.0.0
  integration_test: ^1.0.2+3

  bot_toast: ^4.0.1
  after_layout: ^1.1.0

  firebase_core_platform_interface: ^2.0.0
  firebase_core: ^0.5.3
  firebase_remote_config: ^0.4.3
  firebase_analytics: ^6.3.0
  firebase_crashlytics: ^0.1.4+1
  carousel_slider: ^4.0.0-nullsafety.0
  flutter_svg: ^0.22.0

  # 状態管理（providerの後継）
  # https://riverpod.dev/docs/getting_started/#what-package-to-install
  flutter_riverpod: ^0.14.0+3

  fl_chart: ^0.36.2

  logger: ^1.0.0

  image_picker: ^0.6.7+12
  image_cropper: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  plugin_platform_interface: ^1.0.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/i18n/
    - assets/images/common/
    - assets/images/login/
    - assets/images/user/
    - assets/images/power_plant/
    - assets/images/tutorial/
    - assets/images/sample/
    - assets/fonts/
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Black.otf
          weight: 900
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Bold.otf
          weight: 700
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Medium.otf
          weight: 500
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Regular.otf
          weight: 400
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Light.otf
          weight: 300
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Thin.otf
          weight: 100
    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow/Barlow-Black.ttf
          weight: 900
        - asset: assets/fonts/Barlow/Barlow-Bold.ttf
          weight: 700
        - asset: assets/fonts/Barlow/Barlow-Medium.ttf
          weight: 500
        - asset: assets/fonts/Barlow/Barlow-Regular.ttf
          weight: 400
        - asset: assets/fonts/Barlow/Barlow-Light.ttf
          weight: 300
        - asset: assets/fonts/Barlow/Barlow-Thin.ttf
          weight: 100
