name: minden
description: minden app

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.4+9

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0-nullsafety.2
  equatable: ^2.0.0
  get_it: ^7.1.3
  flutter_bloc: ^7.0.0
  connectivity: ^3.0.6
  url_launcher: ^6.0.3
  flutter_i18n: ^0.22.3
  sprintf: ^6.0.0
  package_info: ^2.0.0
  version: ^2.0.0
  shared_preferences: ^2.0.5

  mockito: ^5.0.0

  bot_toast: ^4.0.1
  after_layout: ^1.1.0
  expandable: ^5.0.1

  firebase_core_platform_interface: ^4.0.1
  firebase_core: ^1.4.0
  firebase_dynamic_links: ^4.0.5
  firebase_remote_config: ^0.10.0+3
  firebase_analytics: ^9.1.0
  firebase_crashlytics: ^2.1.1
  firebase_messaging: ^10.0.4

  flutter_local_notifications: ^8.0.0
  flutter_svg: ^0.22.0

  # UI Component
  fl_chart: ^0.36.2
  carousel_slider: ^4.0.0

  logger: ^1.0.0

  image_picker: ^0.8.2
  image_cropper: ^1.4.1

  # ピュアdartのkey-valueストア
  # https://pub.dev/packages/hive
  hive: ^2.0.4
  # 暗号化鍵の保存用（Android: KeyStore, iOS: Keychainに保存する）
  # https://pub.dev/packages/flutter_secure_storage
  flutter_secure_storage: ^4.2.1

  path_provider: ^2.0.3
  retry: ^3.1.0

  cached_network_image: ^3.1.0

  flutter_native_splash: ^1.1.5+1

  flutter_hooks: ^0.18.0
  hooks_riverpod: ^0.14.0
  freezed_annotation: ^0.14.0

  collection: ^1.15.0

  flutter_linkify: ^5.0.2

  share_plus: ^2.2.0

  decorated_icon: ^1.2.1

dev_dependencies:
  build_runner: 1.12.2
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  freezed: ^0.14.0
  integration_test:
    sdk: flutter
  json_serializable: ^4.1.0
  plugin_platform_interface: ^2.0.1

flutter_native_splash:
  image: "assets/images/login/splash_logo.png"
  color: "FF8C00"

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/i18n/
    - assets/images/common/
    - assets/images/login/
    - assets/images/user/
    - assets/images/power_plant/
    - assets/images/tutorial/
    - assets/images/profile_setting/
    - assets/images/message/
    - assets/images/violate/
    - assets/images/sample/
    - assets/images/support_history/
    - assets/fonts/
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Black.otf
          weight: 900
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Bold.otf
          weight: 700
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Medium.otf
          weight: 500
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Regular.otf
          weight: 400
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Light.otf
          weight: 300
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Thin.otf
          weight: 100
    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow/Barlow-Black.ttf
          weight: 900
        - asset: assets/fonts/Barlow/Barlow-Bold.ttf
          weight: 700
        - asset: assets/fonts/Barlow/Barlow-Medium.ttf
          weight: 500
        - asset: assets/fonts/Barlow/Barlow-Regular.ttf
          weight: 400
        - asset: assets/fonts/Barlow/Barlow-Light.ttf
          weight: 300
        - asset: assets/fonts/Barlow/Barlow-Thin.ttf
          weight: 100

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/common/app_icon.png"
