// Mocks generated by Mockito 5.0.7 from annotations
// in minden/test/features/token/data/datasources/token_data_source_test.dart.
// Do not manually edit this file.

import 'package:minden/features/token/data/datasources/encryption_token_data_source.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

/// A class which mocks [EncryptionTokenDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockEncryptionTokenDataSource extends _i1.Mock
    implements _i2.EncryptionTokenDataSource {
  MockEncryptionTokenDataSource() {
    _i1.throwOnMissingStub(this);
  }
}
